name: build-develop
on:
  push:
    branches:
      - github-ci

jobs:
  build:
    name: Compile
    strategy:
      matrix:
        java_version: [8, 9, 10]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package --file pom.xml
      - run: echo The time was ${{ steps.hello.outputs.time }}


